### ISSUE TITLE
Request to Set Project Repository as Public

### ISSUE THREAD

**Issue by benymaxparsa** [Fall2024-MLProjects/CommunityDetection#1]
Dear Omid,

I hope you’re doing well. 
Would it be possible to set our project repository visibility setting to public? 

This would allow us to include its link in our resumes, CVs, and websites as an achievement or a proper way to showcase our project for job opportunities, and etc.

Thank you for considering this! Kindly let me know if it's possible.

Best regards, Parsa

**Comment by omid-reza** [comment]
Dear Parsa,

The repository has been changed to public.

Best,
Omid Reza Heidari
